version: '3.4'

services:
  traning.microservices.basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DATABASE=Server=traning.microservices.database;Database=Basket_DB;User=sa;Password=My_P@ssword_123;
      - API_URL_CATALOG=http://traning.microservices.catalog
      - JAEGER_SERVICE_NAME=basket
      - JAEGER_AGENT_HOST=traning.microservices.jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
    ports:
      - "60001:80"
      - "44301:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - traning.microservices.database
  traning.microservices.catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DATABASE=Server=traning.microservices.database;Database=Catalog_DB;User=sa;Password=My_P@ssword_123;
      - EVENTBUS_HOSTNAME=traning.microservices.eventbus
      - EVENTBUS_PORT=5672
      - EVENTBUS_USERNAME=rabbitmq
      - EVENTBUS_PASSWORD=rabbitmq
      - EVENTBUS_VHOST=/
      - JAEGER_SERVICE_NAME=catalog
      - JAEGER_AGENT_HOST=traning.microservices.jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
    ports:
      - "60002:80"
      - "44302:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - traning.microservices.database
  traning.microservices.email:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EVENTBUS_HOSTNAME=traning.microservices.eventbus
      - EVENTBUS_PORT=5672
      - EVENTBUS_USERNAME=rabbitmq
      - EVENTBUS_PASSWORD=rabbitmq
      - EVENTBUS_VHOST=/
      - JAEGER_SERVICE_NAME=email
      - JAEGER_AGENT_HOST=traning.microservices.jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
    ports:
      - "60011:80"
      - "44311:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  traning.microservices.eventbus:
    hostname: traning.microservices.eventbus
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/
  traning.microservices.jaeger:
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778" 
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  traning.microservices.database:
    environment:
      - SA_PASSWORD=My_P@ssword_123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
